// Auto-generated by export_regression_coefficients.py
// Trained on April 2026 eval window -> May 2026 OVR update
// Features are % vs uZIPS (positive = outperforming projection)
// Batters: wRC+, OPS, ISO, BABIP, K%, BB% vs uZIPS + old_ovr (R=0.698)
// Pitchers: K/9, HR/9, BB/9, BABIP vs uZIPS, no OVR needed (R=0.750)
// DO NOT EDIT MANUALLY — re-run the script after each monthly update

export const BAT_REGRESSION = {
  intercept: 2.133299,
  r: 0.6982,
  n: 315,
  features: [
    { key: 'wRCp_vs', coeff: -0.09649382, mean: -8.274973, std: 29.804571 },
    { key: 'OPS_vs', coeff: 0.4059415, mean: -3.587359, std: 13.908838 },
    { key: 'ISO_vs', coeff: -0.01859684, mean: -10.734418, std: 30.826915 },
    { key: 'BABIP_vs', coeff: -0.02234465, mean: -2.371412, std: 14.341875 },
    { key: 'Kpct_vs', coeff: -0.0224172, mean: 0.328815, std: 15.516698 },
    { key: 'BBpct_vs', coeff: 0.02509811, mean: 2.563652, std: 27.64997 },
    { key: 'old_ovr', coeff: -0.0417563, mean: 71.488889, std: 13.427845 },
  ]
};

export const PIT_REGRESSION = {
  intercept: -1.487253,
  r: 0.7497,
  n: 310,
  features: [
    { key: 'K9_vs', coeff: 0.0471155, mean: -0.871834, std: 16.153318 },
    { key: 'HR9_vs', coeff: 0.03709641, mean: 14.782383, std: 48.984443 },
    { key: 'BB9_vs', coeff: 0.04366093, mean: -4.936195, std: 27.150686 },
    { key: 'BABIP_vs', coeff: 0.04536329, mean: 3.242459, std: 19.337472 },
  ]
};
