// Auto-generated by retrain_regression.py
// Trained on two months: April + May 2026 eval windows -> May + June 2026 OVR updates
// Combined training set: 555 batters, 534 pitchers
// Features are % vs uZIPS (positive = outperforming projection)
// Batters: wRC+, OPS, ISO, BABIP, K%, BB% vs uZIPS + old_ovr (R=0.666)
// Pitchers: K/9, HR/9, BB/9, BABIP vs uZIPS (R=0.774)
// DO NOT EDIT MANUALLY — re-run retrain_regression.py after each monthly update

export const BAT_REGRESSION = {
  intercept: 3.272836,
  r: 0.6664,
  n: 555,
  features: [
    { key: 'wRCp_vs', coeff: -0.06791326, mean: -5.735417, std: 39.217927 },
    { key: 'OPS_vs', coeff: 0.30899527, mean: -3.63396, std: 19.850913 },
    { key: 'ISO_vs', coeff: -0.02139864, mean: -7.821974, std: 44.552232 },
    { key: 'BABIP_vs', coeff: -0.0282003, mean: -2.492835, std: 21.037291 },
    { key: 'Kpct_vs', coeff: -0.0101707, mean: -0.52714, std: 24.286568 },
    { key: 'BBpct_vs', coeff: 0.01207584, mean: 4.911933, std: 43.050003 },
    { key: 'old_ovr', coeff: -0.04556038, mean: 70.956757, std: 13.018695 },
  ]
};

export const PIT_REGRESSION = {
  intercept: -0.577998,
  r: 0.7739,
  n: 534,
  features: [
    { key: 'K9_vs', coeff: 0.0367438, mean: -0.266797, std: 23.416993 },
    { key: 'HR9_vs', coeff: 0.02697318, mean: 10.370064, std: 68.878142 },
    { key: 'BB9_vs', coeff: 0.02836871, mean: -7.259673, std: 45.138754 },
    { key: 'BABIP_vs', coeff: 0.04085198, mean: 4.331654, std: 23.357388 },
  ]
};
