// Auto-generated by export_regression_coefficients.py
// Trained on April 2026 eval window → May 2026 OVR update
// DO NOT EDIT MANUALLY — re-run the script after each monthly update

export const BAT_REGRESSION = {
  intercept: -9.922794,
  r: 0.6591,
  n: 355,
  features: [
    { key: 'wRCp', coeff: -0.05349618, mean: 95.570448, std: 41.809229 },
    { key: 'OPS', coeff: 31.84865012, mean: 0.70016, std: 0.151873 },
    { key: 'ISO', coeff: -7.27464826, mean: 0.144183, std: 0.07408 },
    { key: 'BABIP', coeff: -3.19676864, mean: 0.289805, std: 0.062757 },
    { key: 'BBpct', coeff: 11.62518495, mean: 0.092435, std: 0.043166 },
    { key: 'Kpct', coeff: 2.47946301, mean: 0.223015, std: 0.071108 },
    { key: 'old_ovr', coeff: -0.11313122, mean: 70.543662, std: 13.315677 },
  ]
};

export const PIT_REGRESSION = {
  intercept: 13.986939,
  r: 0.7021,
  n: 347,
  features: [
    { key: 'FIP', coeff: -0.99286814, mean: 4.104626, std: 1.681642 },
    { key: 'ERA', coeff: 0.02928278, mean: 4.285588, std: 2.383441 },
    { key: 'WHIP', coeff: -2.92657354, mean: 1.345148, std: 0.396268 },
    { key: 'K9', coeff: -0.258035, mean: 8.896506, std: 2.465608 },
    { key: 'BB9', coeff: 2.6973632, mean: 3.759116, std: 1.880723 },
    { key: 'HR9', coeff: -0.19576136, mean: 1.069332, std: 0.910656 },
    { key: 'BABIP', coeff: -5.29840136, mean: 0.291977, std: 0.075898 },
    { key: 'Kpct', coeff: 12.24432089, mean: 0.231403, std: 0.066719 },
    { key: 'BBpct', coeff: -113.87728211, mean: 0.095184, std: 0.040756 },
    { key: 'IP', coeff: 0.05093193, mean: 21.826801, std: 11.694837 },
    { key: 'old_ovr', coeff: -0.08939037, mean: 71.602305, std: 12.160208 },
  ]
};
